linters:
  enable:
    - errcheck
    - revive
    - govet
    - ineffassign
    - lll
    - gosimple
    - staticcheck
    - unused
    - misspell
    - nakedret
    - unconvert
    - unused
  enable-all: false
linters-settings:
  lll:
    line-length: 250
run:
  timeout: 10m
